import { JobItem, RECOMMENDED_JOBS, CourseItem, RECOMMENDED_COURSES } from "@/components/dashboard/DashboardShared";
import { BeneficiaryProfileData } from "@/components/onboarding/PersonalVoiceOnboarding";
import { ALL_EXPANDED_NSQF_COURSES } from "@/lib/skillTrainingGenerator";

export type JobSectorCategory =
  | "all"
  | "technical"
  | "agriculture"
  | "self_employment"
  | "digital_construction"
  | "healthcare"
  | "government"
  | "private"
  | "apprenticeship";

export interface EnrichedJobItem extends JobItem {
  sectorId: string;
  sectorName: string;
  nsqfLevel: number;
  qpCode: string;
  trainingCourseId?: string;
  trainingCourseTitle?: string;
  subsidyGrant?: string;
  urgency?: "immediate" | "high" | "normal";
  voiceKeywords: string[];
  district: string;
  state: string;
  salaryNumericMin: number;
  salaryNumericMax: number;
  isDetectedJob?: boolean;
  detectedReason?: string;
}

/**
 * 36+ Comprehensive Verified Jobs and Opportunities directly aligned with NSQF Training Sections
 */
export const COMPREHENSIVE_JOBS_DATABASE: EnrichedJobItem[] = [
  // =========================================================================
  // 1. GREEN ENERGY & TECHNICAL TRADES
  // =========================================================================
  {
    id: "job-solar-field-eng",
    title: "Solar PV Installation & Field Maintenance Technician",
    company: "Adani Solar & GreenGrid Odisha Ltd.",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Kalahandi & Sundargarh",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 18,000 – 28,000/month",
    salaryNumericMin: 18000,
    salaryNumericMax: 28000,
    badge: "PM-KUSUM Priority",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Solar PV", "Submersible Pump", "Inverter Wiring", "High Voltage Safety"],
    category: "private",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "SGJ/Q0101",
    trainingCourseId: "nsqf-course-solar-agri-pump",
    trainingCourseTitle: "Solar PV Agri-Pump Specialist (NSQF Level 4)",
    subsidyGrant: "₹35,000 PM-AJAY Tool Kit Grant",
    urgency: "immediate",
    description: "Install, test and service PM-KUSUM farm solar pumps, DC/AC controllers and micro-grids across 12 Gram Panchayats with company bike and fuel allowance.",
    openings: 28,
    experience: "0-2 Years (Freshers with Suryamitra / NSQF Level 4 Certificate)",
    benefits: ["PF + ESI Healthcare", "Free Solar Tool Bag", "₹400/Site Travel Allowance", "Annual Safety Bonus"],
    contactPhone: "+91 6670 255100",
    verifiedNCS: true,
    voiceKeywords: ["solar", "pump", "solar technician", "suryamitra", "kusum", "solar job", "solar opening", "सोलर", "सोलर नौकरी", "ସୋଲାର"]
  },
  {
    id: "job-5",
    title: "PM Surya Ghar Rooftop Solar Technician",
    company: "Tata Power Solar Discom Services",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Bhawanipatna Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 25,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 25000,
    badge: "High Demand",
    badgeColor: "blue",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Rooftop PV Mounting", "Net Metering", "Discom CEIG Safety"],
    category: "private",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "SGJ/Q0101",
    trainingCourseId: "nsqf-course-solar-rooftop-tech",
    trainingCourseTitle: "Solar Rooftop & Micro-Grid Technician (NSQF Level 4)",
    subsidyGrant: "₹35,000 Capital Subsidy for Solar Tooling",
    urgency: "high",
    description: "Assemble and commission 3kW–10kW rooftop solar power systems under PM Surya Ghar Muft Bijli Yojana with bi-directional net-metering synchronization.",
    openings: 35,
    experience: "Fresher / NSQF Level 4 or ITI Electrical",
    benefits: ["Incentive of ₹300 per kW installed", "Accidental Insurance ₹5 Lakhs", "Company Bike Pass"],
    contactPhone: "+91 6670 255201",
    verifiedNCS: true,
    voiceKeywords: ["rooftop solar", "surya ghar", "solar panel installer", "net metering", "रूफटॉप सोलर", "ଛାତ ସୋଲାର"]
  },
  {
    id: "job-ev-service-tech",
    title: "E-Rickshaw & EV Two-Wheeler Service Technician",
    company: "Mahindra Last Mile Mobility & Yatri EV Hub",
    companyLogoType: "shree",
    type: "Full Time",
    location: "District Transit Hub, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 18,000 – 30,000/month",
    salaryNumericMin: 18000,
    salaryNumericMax: 30000,
    badge: "Emerging Tech",
    badgeColor: "purple",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Li-Ion Battery BMS", "BLDC Hub Motor", "Controller Wiring", "EV Fast Charging"],
    category: "private",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "AUT/Q0101",
    trainingCourseId: "nsqf-course-ev-servicing",
    trainingCourseTitle: "Electric Vehicle (EV) 2W/3W & E-Rickshaw Technician (NSQF Level 4)",
    subsidyGrant: "₹40,000 EV Garage Setup Grant",
    urgency: "high",
    description: "Diagnose electric 2-wheeler scooters and commercial 3-wheeler E-rickshaws, replace BMS sensors, test cell capacity, and service BLDC hub motors.",
    openings: 22,
    experience: "0-1 Year (Automotive or Electrical ITI / NSQF Certificate)",
    benefits: ["OEM Certification from Mahindra EV", "Overtime 1.5x Pay", "Free EV Diagnostic Tablet"],
    contactPhone: "+91 6670 260114",
    verifiedNCS: true,
    voiceKeywords: ["ev", "electric vehicle", "e-rickshaw", "battery", "bms", "scooter repair", "ईवी", "ई-रिक्शा", "ଇ-ରିକ୍ସା"]
  },
  {
    id: "job-biogas-plant-operator",
    title: "Community Biogas & GOBAR-dhan Plant Chief Operator",
    company: "Swachh Bharat Grameen & Gram Panchayat Cell",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Junagarh Block",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 15,000 – 24,000/month",
    salaryNumericMin: 15000,
    salaryNumericMax: 24000,
    badge: "Government",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/food_processing.jpg",
    skills: ["Anaerobic Digestion", "Slurry Separation", "Biogas Bottling", "Safety Valves"],
    category: "government",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "SGJ/Q0601",
    trainingCourseId: "nsqf-course-biogas-plant-operator",
    trainingCourseTitle: "Biogas & Rural Waste-to-Energy Plant Operator (NSQF Level 4)",
    subsidyGrant: "₹45,000 Community Bio-Gas Capital Grant",
    urgency: "normal",
    description: "Manage village cattle dung feeding, monitor digester temperature, operate H2S scrubbers, and distribute enriched organic fertilizer slurry to local farmers.",
    openings: 12,
    experience: "10th Pass with Vocational Skill Certification",
    benefits: ["Government Contract Experience Certificate", "Quarterly Organic Manure Sales Incentive", "Free Uniform & Safety Boots"],
    contactPhone: "+91 6670 220088",
    verifiedNCS: true,
    voiceKeywords: ["biogas", "gobar dhan", "waste to energy", "slurry", "bio-gas", "बायोगैस", "गोबर धन", "ବାୟୋଗ୍ୟାସ"]
  },
  {
    id: "job-tractor-mechanic-lead",
    title: "Farm Tractor & 4W Diesel Mechanic Lead",
    company: "Mahindra & Swaraj Farm Equipment Dealer Hub",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Bhawanipatna Mandi Area",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 18,000 – 32,000/month",
    salaryNumericMin: 18000,
    salaryNumericMax: 32000,
    badge: "Essential Service",
    badgeColor: "blue",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Tractor Hydraulics", "CRDI Diesel Overhaul", "OBD-II Scanning", "Brake Lining"],
    category: "private",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "ASC/Q1401",
    trainingCourseId: "nsqf-course-auto-tractor-mechanic",
    trainingCourseTitle: "2W/4W Auto Mechanic & Farm Tractor Service Hub (NSQF Level 4)",
    subsidyGrant: "₹40,000 Capital Subsidy for Hydraulic Lift",
    urgency: "high",
    description: "Service agricultural tractors, overhaul hydraulic 3-point lift linkages, calibrate rotary diesel fuel injection pumps, and provide emergency on-field farm support.",
    openings: 18,
    experience: "1-3 Years (Tractor/Automotive workshop)",
    benefits: ["Performance Commission per tractor serviced", "Tool Chest provided", "Medical Insurance"],
    contactPhone: "+91 6670 244109",
    verifiedNCS: true,
    voiceKeywords: ["tractor", "mechanic", "tractor mechanic", "diesel engine", "auto mechanic", "ट्रैक्टर", "मैकेनिक", "ଟ୍ରାକ୍ଟର ମିସ୍ତ୍ରୀ"]
  },
  {
    id: "job-1",
    title: "DISCOM Substation Assistant Wireman & Metering Tech",
    company: "TP Western Odisha Distribution Ltd (TPWODL)",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Kalahandi Central Substation",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 15,000 – 22,000/month",
    salaryNumericMin: 15000,
    salaryNumericMax: 22000,
    badge: "Government",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["Single/3-Phase Wiring", "Smart Net Metering", "Transformer Earthing", "Safety Protocol"],
    category: "government",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "ELE/Q5901",
    trainingCourseId: "course-1",
    trainingCourseTitle: "Electrician (NSQF Level 4)",
    subsidyGrant: "₹35,000 PM-AJAY Tool Kit Grant",
    urgency: "high",
    description: "Inspect residential power distribution connections, install smart digital electricity meters, perform transformer earthing tests, and resolve supply outages.",
    openings: 25,
    experience: "ITI Electrician or NSQF Level 4 Certificate",
    benefits: ["Government Grade EPF & ESI", "Govt ID Card & Service Quarters priority", "Subsidized Canteen"],
    contactPhone: "+91 6670 221144",
    verifiedNCS: true,
    voiceKeywords: ["electrician", "bijli", "wireman", "discom", "substation", "metering", "इलेक्ट्रीशियन", "बिजली", "ଇଲେକ୍ଟ୍ରିସିଆନ୍"]
  },
  {
    id: "job-mobile-smd-lead",
    title: "Mobile Hardware & SMD Diagnostics Lead",
    company: "Digital India Micro-Repair Services Ltd.",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Kalahandi ITI Market",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 26,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 26000,
    badge: "High Growth",
    badgeColor: "blue",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["SMD Desoldering", "Screen Lamination", "Microscope Diagnostics", "Software Flashing"],
    category: "private",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "ELE/Q4605",
    trainingCourseId: "course-7",
    trainingCourseTitle: "Mobile Hardware & SMD Diagnostics (NSQF Level 4)",
    subsidyGrant: "₹35,000 Micro-Diagnostic Kit Grant",
    urgency: "normal",
    description: "Perform precision smartphone PCB micro-soldering, charging IC replacements, touch screen OCA lamination, and software recovery across multi-brand devices.",
    openings: 14,
    experience: "Fresher with NSQF Level 4 / 6 Months Repair experience",
    benefits: ["Incentive per device repaired", "Clean AC Lab Environment", "Annual Skill Upgrade"],
    contactPhone: "+91 6670 248900",
    verifiedNCS: true,
    voiceKeywords: ["mobile repair", "phone repair", "smd", "chip level", "screen replacement", "मोबाइल रिपेयर", "ମୋବାଇଲ ମରାମତି"]
  },

  // =========================================================================
  // 2. AGRICULTURE, HORTICULTURE & ALLIED ENTERPRISE
  // =========================================================================
  {
    id: "job-kisan-drone-pilot",
    title: "Commercial Kisan Drone Spraying Pilot",
    company: "Garuda Aerospace / IFFCO Kisan Drone Fleet",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Kalahandi Agri Cluster",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 22,000 – 35,000/month",
    salaryNumericMin: 22000,
    salaryNumericMax: 35000,
    badge: "DGCA Certified",
    badgeColor: "purple",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["DGCA Drone Flight", "Nano-Urea Spraying", "GIS Mapping", "LiPo Battery Safety"],
    category: "private",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 4,
    qpCode: "AGR/Q4901",
    trainingCourseId: "nsqf-course-drone-pilot-agri",
    trainingCourseTitle: "Kisan Drone Pilot & Crop Health Analyst (NSQF Level 4)",
    subsidyGrant: "₹50,000 Drone SHG Hub Grant",
    urgency: "immediate",
    description: "Fly 10L–20L agricultural spraying drones for precision nano-fertilizer and bio-pesticide distribution across paddy and cotton clusters with per-acre bonus.",
    openings: 20,
    experience: "DGCA Remote Pilot License or NSQF Level 4 Drone Course",
    benefits: ["₹50/Acre Spraying Bonus (Earn ₹12,000+ extra/mo)", "Drone Flight Insurance", "Travel Van Provided"],
    contactPhone: "+91 6670 270150",
    verifiedNCS: true,
    voiceKeywords: ["drone", "kisan drone", "drone pilot", "drone spraying", "uav", "ड्रोन", "किसान ड्रोन", "ଡ୍ରୋନ୍ ପାଇଲଟ"]
  },
  {
    id: "job-chc-drone-enterprise",
    title: "Custom Hiring Center (CHC) Drone Hub Entrepreneur",
    company: "PM-AJAY FPO Custom Hiring Hub",
    companyLogoType: "odisha",
    type: "Self-Employment",
    location: "Dharmagarh & Junagarh",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 35,000 – 65,000/month (Net Margin)",
    salaryNumericMin: 35000,
    salaryNumericMax: 65000,
    badge: "PM-AJAY Grant",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Drone Fleet Service", "FPO Cluster Linkage", "Autonomous Flight Mission", "Digital Billing"],
    category: "self_employment",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 4,
    qpCode: "AGR/Q4901",
    trainingCourseId: "nsqf-course-drone-pilot-agri",
    trainingCourseTitle: "Kisan Drone Pilot & Crop Health Analyst (NSQF Level 4)",
    subsidyGrant: "₹50,000 Direct PM-AJAY Subsidy + 80% Drone CHC Subsidy",
    urgency: "high",
    description: "Launch an independent village Kisan Drone Custom Hiring Center. Provide aerial spraying, crop health indexing, and seed bombing to 250+ village farm holdings.",
    openings: 15,
    experience: "Open to Rural Youth & Women SHG leads",
    benefits: ["100% Subsidized Pilot Training", "Pre-tied contract with 12 Farmer Producer Orgs (FPOs)", "Direct DBT Subsidy"],
    contactPhone: "+91 6670 270210",
    verifiedNCS: true,
    voiceKeywords: ["drone enterprise", "chc drone", "drone business", "drone subsidy", "ड्रोन स्वरोजगार", "ଡ୍ରୋନ୍ ବ୍ୟବସାୟ"]
  },
  {
    id: "job-mushroom-production-sup",
    title: "Commercial Mushroom & Spawn Lab Supervisor",
    company: "Orissa Rural Mushroom Producers Consortium",
    companyLogoType: "ahaar",
    type: "Full Time",
    location: "Kalahandi Agri Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 14,000 – 22,000/month",
    salaryNumericMin: 14000,
    salaryNumericMax: 22000,
    badge: "High Profit",
    badgeColor: "emerald",
    badgeIcon: "chart",
    image: "/dashboard/food_processing.jpg",
    skills: ["Spawn Culture", "Humidity Chambers", "Oyster & Button Cropping", "FSSAI Packaging"],
    category: "private",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 3,
    qpCode: "AGR/Q0801",
    trainingCourseId: "nsqf-course-organic-mushroom",
    trainingCourseTitle: "Commercial Mushroom & Spawn Production (NSQF Level 3)",
    subsidyGrant: "₹35,000 Mushroom Shed Capital Grant",
    urgency: "normal",
    description: "Supervise substrate pasteurization, inoculate sterile master spawn, manage automated humidity misting chambers, and package fresh mushrooms for supermarket supply.",
    openings: 16,
    experience: "Fresher / NSQF Level 3 Mushroom Certification",
    benefits: ["Free Spawn Starter Kit", "Production Output Bonus", "Day Shift Only"],
    contactPhone: "+91 6670 245330",
    verifiedNCS: true,
    voiceKeywords: ["mushroom", "spawn", "mushroom farming", "organic mushroom", "मशरूम", "मशरूम फार्मिंग", "ଛତୁ ଚାଷ"]
  },
  {
    id: "job-omfed-dairy-lead",
    title: "Bulk Milk Chilling & Dairy Value-Addition Supervisor",
    company: "OMFED (Odisha State Cooperative Milk Producers)",
    companyLogoType: "odisha",
    type: "Full Time",
    location: "Junagarh Dairy Chilling Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 26,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 26000,
    badge: "Government Co-op",
    badgeColor: "blue",
    badgeIcon: "building",
    image: "/dashboard/food_processing.jpg",
    skills: ["Bulk Milk Cooler (BMC)", "Fat & SNF Testing", "Paneer/Ghee Processing", "Cold Chain Logistics"],
    category: "government",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 4,
    qpCode: "AGR/Q4101",
    trainingCourseId: "nsqf-course-dairy-processing",
    trainingCourseTitle: "Dairy Processing & Milk Value-Addition Hub (NSQF Level 4)",
    subsidyGrant: "₹45,000 Mini Milk Chilling Unit Subsidy",
    urgency: "high",
    description: "Manage daily village milk collection, operate automated ultrasonic Fat/SNF milk analyzers, oversee 4°C bulk chilling units, and process fresh hygienic paneer and curd.",
    openings: 18,
    experience: "10th / 12th Pass with Dairy Processing Certificate",
    benefits: ["Cooperative Society Job Security", "ESI & Provident Fund", "Quarterly Milk Volume Incentive"],
    contactPhone: "+91 6670 230911",
    verifiedNCS: true,
    voiceKeywords: ["dairy", "milk", "omfed", "chilling center", "paneer", "ghee", "डेयरी", "दूध", "ଡାଏରୀ", "ଦୁଗ୍ଧ"]
  },
  {
    id: "job-honey-apiary-lead",
    title: "Pure Raw Honey Apiary & Bee Wax Studio Owner",
    company: "KVIC Tribal Honey Processing Center",
    companyLogoType: "shree",
    type: "Self-Employment",
    location: "Fringe Forest Belts, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 20,000 – 38,000/month (Net)",
    salaryNumericMin: 20000,
    salaryNumericMax: 38000,
    badge: "KVIC Supported",
    badgeColor: "amber",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Langstroth Bee Boxes", "Queen Rearing", "Honey Extraction", "Bee Wax Candle Making"],
    category: "self_employment",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 3,
    qpCode: "AGR/Q1101",
    trainingCourseId: "nsqf-course-apiculture-honey",
    trainingCourseTitle: "Commercial Honey Bee Keeping & Processing (NSQF Level 3)",
    subsidyGrant: "₹30,000 KVIC Grant + 10 Free Bee Boxes",
    urgency: "normal",
    description: "Establish a scientific apiary using 10+ modern Langstroth boxes. Harvest high-purity wild floral honey and refine cosmetic bee wax with guaranteed TRIFED buyback.",
    openings: 25,
    experience: "Open to Forest Dwellers & Small Farmers",
    benefits: ["100% Guaranteed Buyback by TRIFED", "20-30% higher surrounding crop pollination yield", "Pure Agmark Certification"],
    contactPhone: "+91 6670 266400",
    verifiedNCS: true,
    voiceKeywords: ["honey", "bee", "beekeeping", "apiculture", "kvic", "मधुमक्खी", "शहद", "ମହୁ ଚାଷ"]
  },
  {
    id: "job-poultry-hatchery-owner",
    title: "Solar Backyard Poultry Hatchery Owner (Kadaknath/Kuroiler)",
    company: "National Livestock Mission / PM-AJAY Cell",
    companyLogoType: "odisha",
    type: "Self-Employment",
    location: "Gram Panchayat Level",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 25,000 – 45,000/month",
    salaryNumericMin: 25000,
    salaryNumericMax: 45000,
    badge: "High Turnover",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Solar Incubator", "Vaccination Schedule", "Organic Brooding", "Poultry Feed Blending"],
    category: "self_employment",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 3,
    qpCode: "AGR/Q4301",
    trainingCourseId: "nsqf-course-poultry-hatchery",
    trainingCourseTitle: "Poultry & Backyard Hatchery Specialist (NSQF Level 3)",
    subsidyGrant: "₹35,000 PM-AJAY Poultry Capital Subsidy",
    urgency: "high",
    description: "Operate a solar-powered egg incubator, brood day-old Kuroiler & Kadaknath chicks, maintain vaccination protocols, and supply premium poultry to weekly rural haats.",
    openings: 30,
    experience: "Functional Literacy & Passion for Livestock",
    benefits: ["50 Free Kuroiler Starter Chicks", "Weekly cash collections from eggs & meat", "Veterinary doctor visit support"],
    contactPhone: "+91 6670 238120",
    verifiedNCS: true,
    voiceKeywords: ["poultry", "chicken", "hatchery", "murgi", "kadaknath", "kuroiler", "पोल्ट्री", "मुर्गी पालन", "କୁକୁଡ଼ା ଚାଷ"]
  },
  {
    id: "job-biofloc-aqua-tech",
    title: "High-Density Biofloc Fish Tank Farm Operator",
    company: "PM Matsya Sampada Yojana (PMMSY) Aqua Cluster",
    companyLogoType: "shree",
    type: "Full Time",
    location: "Bhawanipatna Fishery Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 18,000 – 28,000/month",
    salaryNumericMin: 18000,
    salaryNumericMax: 28000,
    badge: "PMMSY Linked",
    badgeColor: "blue",
    badgeIcon: "chart",
    image: "/dashboard/food_processing.jpg",
    skills: ["Biofloc Microbial Culture", "DO Aeration Blowers", "Water Testing (pH/Ammonia)", "Fish Harvesting"],
    category: "private",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 4,
    qpCode: "AGR/Q5101",
    trainingCourseId: "nsqf-course-aquaculture-biofloc",
    trainingCourseTitle: "Fisheries, Biofloc Farming & Aqua-Tech Hub (NSQF Level 4)",
    subsidyGrant: "₹50,000 PM-AJAY Subsidy + 60% PMMSY Grant",
    urgency: "normal",
    description: "Manage intensive circular HDPE Biofloc tanks, monitor probiotic C:N balance, calibrate aeration blowers, feed Rohu/Catla fingerlings, and pack live fish for urban mandis.",
    openings: 15,
    experience: "Fresher / NSQF Level 4 Fisheries Certification",
    benefits: ["Direct tie-up with live fish transport network", "Performance bonus on harvesting cycle", "ESI Healthcare"],
    contactPhone: "+91 6670 259040",
    verifiedNCS: true,
    voiceKeywords: ["fish", "fisheries", "biofloc", "matsya", "prawn", "aqua", "मछली पालन", "बायोफ्लॉक", "ମାଛ ଚାଷ"]
  },
  {
    id: "job-vermicompost-hub-mgr",
    title: "Organic Vermicompost & Bio-Fertilizer Unit Manager",
    company: "Krishi Vigyan Kendra FPO Supplier Network",
    companyLogoType: "ahaar",
    type: "Self-Employment",
    location: "Kalahandi KVK Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 14,000 – 22,000/month",
    salaryNumericMin: 14000,
    salaryNumericMax: 22000,
    badge: "PM-AJAY Grant",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Earthworm Culture (Eisenia Fetida)", "Trichoderma Enrichment", "Moisture Monitoring", "Bagging & FCO Compliance"],
    category: "self_employment",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 3,
    qpCode: "AGR/Q1201",
    trainingCourseId: "course-8",
    trainingCourseTitle: "Organic Farming & Vermicompost Hub (NSQF Level 3)",
    subsidyGrant: "₹35,000 Seed Capital Grant",
    urgency: "normal",
    description: "Establish vermicompost beds using agricultural straw and cow dung. Harvest high-nutrient black gold vermicompost, pack in 25kg/50kg bags, and supply to 12 local FPOs.",
    openings: 40,
    experience: "Small & Marginal Farmers",
    benefits: ["₹35,000 PM-AJAY capital grant", "Pre-approved purchase orders from FPOs", "Certified organic input seller license"],
    contactPhone: "+91 6670 220199",
    verifiedNCS: true,
    voiceKeywords: ["vermicompost", "organic farming", "fertilizer", "earthworm", "khad", "वर्मीकम्पोस्ट", "जैविक खाद", "ଜୈବିକ ଖତ"]
  },

  // =========================================================================
  // 3. HANDICRAFTS, TRADITIONAL TEXTILES & WOMEN SHG
  // =========================================================================
  {
    id: "job-handloom-jacquard-lead",
    title: "Jacquard Handloom Master Artisan & Exporter",
    company: "Boyanika Handloom Weaver Cooperative Society",
    companyLogoType: "sakhi",
    type: "Full Time",
    location: "Weaver Cluster, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 18,000 – 30,000/month",
    salaryNumericMin: 18000,
    salaryNumericMax: 30000,
    badge: "GI Tag Certified",
    badgeColor: "amber",
    badgeIcon: "star",
    image: "/dashboard/tailoring.jpg",
    skills: ["Jacquard Loom", "Organic Dyeing", "Tussar Silk Weaving", "ONDC Cataloging"],
    category: "private",
    sectorId: "crafts_textiles",
    sectorName: "Handicrafts & Women SHG",
    nsqfLevel: 4,
    qpCode: "TSC/Q2201",
    trainingCourseId: "nsqf-course-handloom-jacquard",
    trainingCourseTitle: "Jacquard Handloom & Traditional Textile Master (NSQF Level 4)",
    subsidyGrant: "₹45,000 Jacquard Loom Subsidy",
    urgency: "normal",
    description: "Weave authentic GI-tagged Sambalpuri & Habaspuri tribal motif sarees on modern pit/frame looms with direct procurement by Boyanika and international fashion buyers.",
    openings: 22,
    experience: "Artisans with basic loom knowledge / NSQF Certificate",
    benefits: ["Boyanika Certified Artisan Card", "Free Yarn Subsidy worth ₹15,000/quarter", "Silk Mark Labeling"],
    contactPhone: "+91 6670 231450",
    verifiedNCS: true,
    voiceKeywords: ["handloom", "weaving", "jacquard", "saree", "boyanika", "tussar", "हथकरघा", "हैंडलूम", "ବୁଣାକାର", "ଶାଢ଼ୀ"]
  },
  {
    id: "job-2",
    title: "Industrial Apparel Sewing Machine Operator & Batch Supervisor",
    company: "Sakhi Garments Export Hub / Shahi Exports",
    companyLogoType: "sakhi",
    type: "Full Time",
    location: "Women SHG Cluster, Junagarh",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 13,000 – 19,500/month",
    salaryNumericMin: 13000,
    salaryNumericMax: 19500,
    badge: "SHG Enterprise",
    badgeColor: "purple",
    badgeIcon: "thumbs_up",
    image: "/dashboard/tailoring.jpg",
    skills: ["Industrial Sewing Machine (SNLS)", "Pattern Drafting", "Quality Audit", "Overlock Stitching"],
    category: "private",
    sectorId: "crafts_textiles",
    sectorName: "Handicrafts & Women SHG",
    nsqfLevel: 3,
    qpCode: "AMH/Q0102",
    trainingCourseId: "course-2",
    trainingCourseTitle: "Tailoring & Apparel (NSQF Level 3)",
    subsidyGrant: "₹4,000/mo Stipend + Free Sewing Machine",
    urgency: "immediate",
    description: "Operate high-speed motorized industrial sewing machines for bulk school uniforms, kurtas, and export garments under safe women-centric SHG federation workshop.",
    openings: 35,
    experience: "0-1 Year (Basic Stitching Knowledge)",
    benefits: ["Piece-Rate Production Bonus", "Safe Women Workplace & Free Crèche", "Subsidized Lunch Canteen", "Free Motorized Machine on graduation"],
    contactPhone: "+91 6670 231190",
    verifiedNCS: true,
    voiceKeywords: ["tailor", "sewing", "silai", "garment", "stitching", "boutique", "सिलाई", "दर्जी", "ସିଲେଇ", "ଲୁଗା"]
  },
  {
    id: "job-bamboo-craft-designer",
    title: "Bamboo Lifestyle Homeware & Eco-Craft Designer",
    company: "TRIFED Tribal Lifestyle Studio",
    companyLogoType: "shree",
    type: "Self-Employment",
    location: "Artisan Village Hub, Junagarh",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 22,000 – 40,000/month (Net)",
    salaryNumericMin: 22000,
    salaryNumericMax: 40000,
    badge: "TRIFED Partner",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/tailoring.jpg",
    skills: ["Bamboo Seasoning", "Precision Slivering", "Eco Furniture", "Amazon Karigar Sales"],
    category: "self_employment",
    sectorId: "crafts_textiles",
    sectorName: "Handicrafts & Women SHG",
    nsqfLevel: 3,
    qpCode: "HCS/Q8701",
    trainingCourseId: "nsqf-course-bamboo-craft-design",
    trainingCourseTitle: "Bamboo Craft Design & Eco-Lifestyle Products (NSQF Level 3)",
    subsidyGrant: "₹35,000 Capital Subsidy for Bamboo Tooling",
    urgency: "normal",
    description: "Manufacture eco-friendly bamboo lampshades, modular furniture, baskets, and lifestyle decor with direct onboarding on TRIFED Tribes India & Amazon Karigar.",
    openings: 20,
    experience: "Open to Tribal Artisans & Creative Youth",
    benefits: ["₹10,000 Raw Material Grant", "Direct buyer exhibitions at Dilli Haat & Saras Mela", "Export grade packaging support"],
    contactPhone: "+91 6670 262300",
    verifiedNCS: true,
    voiceKeywords: ["bamboo", "craft", "artisan", "cane", "furniture", "trifed", "बांस", "हस्तशिल्प", "ବାଉଁଶ କାମ"]
  },
  {
    id: "job-terracotta-railway-kulhad",
    title: "Terracotta Ceramic Cookware & Railway Kulhad Supplier",
    company: "Indian Railways Eco-Catering & KVIC Pottery Center",
    companyLogoType: "shree",
    type: "Self-Employment",
    location: "Kalahandi Pottery Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 20,000 – 38,000/month",
    salaryNumericMin: 20000,
    salaryNumericMax: 38000,
    badge: "KVIC Supported",
    badgeColor: "amber",
    badgeIcon: "star",
    image: "/dashboard/tailoring.jpg",
    skills: ["Electric Potter Wheel", "Pugmill Clay Blending", "Downdraft Kiln Firing", "Non-Toxic Glazing"],
    category: "self_employment",
    sectorId: "crafts_textiles",
    sectorName: "Handicrafts & Women SHG",
    nsqfLevel: 3,
    qpCode: "HCS/Q0701",
    trainingCourseId: "nsqf-course-terracotta-pottery",
    trainingCourseTitle: "Terracotta, Ceramic Pottery & Earthenware Studio (NSQF Level 3)",
    subsidyGrant: "Free Electric Wheel + ₹35,000 Pottery Kiln Grant",
    urgency: "high",
    description: "Operate motorized electric potter wheels to produce uniform terracotta tea kulhads for Indian Railways catering and non-toxic earthen cookware handis for retail.",
    openings: 30,
    experience: "Traditional Potters & Rural Youth",
    benefits: ["Free Variable Speed Electric Potter Wheel", "Bulk purchase orders from IRCTC Railway Stalls", "Zero smoke kiln subsidy"],
    contactPhone: "+91 6670 263411",
    verifiedNCS: true,
    voiceKeywords: ["pottery", "clay", "terracotta", "kulhad", "potter", "कुम्हार", "कुल्हड़", "टेराकोटा", "ମାଟି ପାତ୍ର", "କୁମ୍ଭାର"]
  },
  {
    id: "job-beauty-wellness-salon",
    title: "Women Beauty Salon & Bridal Wellness Entrepreneur",
    company: "Pragati Women Empowerment SHG Federation",
    companyLogoType: "sakhi",
    type: "Self-Employment",
    location: "Dharmagarh & Bhawanipatna",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 22,000 – 42,000/month (Net)",
    salaryNumericMin: 22000,
    salaryNumericMax: 42000,
    badge: "Self-Employment",
    badgeColor: "purple",
    badgeIcon: "star",
    image: "/dashboard/tailoring.jpg",
    skills: ["Skin Care & Facial", "Bridal Makeup", "Herbal Hair Spa", "Mudra Micro-Loan Management"],
    category: "self_employment",
    sectorId: "crafts_textiles",
    sectorName: "Handicrafts & Women SHG",
    nsqfLevel: 3,
    qpCode: "BWS/Q0102",
    trainingCourseId: "course-10",
    trainingCourseTitle: "Beauty & Wellness Therapist (NSQF Level 3)",
    subsidyGrant: "₹3,500/mo Stipend + Beauty Parlour Starter Kit",
    urgency: "normal",
    description: "Establish a village-level women beauty parlour and bridal grooming hub supported by PM Mudra Shishu loan and PM-AJAY women enterprise grant.",
    openings: 25,
    experience: "8th Standard onwards with Beauty & Wellness Certification",
    benefits: ["Complete professional parlour makeup kit", "Direct bank tie-up for ₹50,000 collateral-free loan", "High festive bridal demand"],
    contactPhone: "+91 6670 234190",
    verifiedNCS: true,
    voiceKeywords: ["beauty", "parlour", "salon", "makeup", "bridal", "wellness", "ब्यूटी पार्लर", "मेकअप", "ବିୟୁଟି ପାର୍ଲର"]
  },

  // =========================================================================
  // 4. DIGITAL, INFRASTRUCTURE & CONSTRUCTION
  // =========================================================================
  {
    id: "job-csc-egram-officer",
    title: "Common Service Center (CSC) & e-Gram Citizen Services Officer",
    company: "CSC e-Governance Services India Ltd.",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Gram Panchayat Kendra",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 15,000 – 25,000/month",
    salaryNumericMin: 15000,
    salaryNumericMax: 25000,
    badge: "Govt Services",
    badgeColor: "blue",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["AePS Micro-ATM", "Aadhaar e-KYC", "PM-Kisan DBT", "DigiLocker"],
    category: "government",
    sectorId: "digital_construction",
    sectorName: "Digital, Infrastructure & Construction",
    nsqfLevel: 4,
    qpCode: "SSC/Q1401",
    trainingCourseId: "nsqf-course-csc-digital-gram",
    trainingCourseTitle: "Common Service Center (CSC) & Digital e-Gram Operator (NSQF Level 4)",
    subsidyGrant: "₹35,000 Digital Kiosk Setup Subsidy",
    urgency: "high",
    description: "Provide Aadhaar enabled banking cash withdrawals (AePS), issue Ayushman cards, process PM-Kisan e-KYC, utility bills, and submit student scholarship forms at village kiosk.",
    openings: 30,
    experience: "10th / 12th Pass with Basic Computer Proficiency",
    benefits: ["High recurring service commission model", "Government VLE ID card & Digital India Branding", "Work in your home Gram Panchayat"],
    contactPhone: "+91 6670 220055",
    verifiedNCS: true,
    voiceKeywords: ["csc", "computer", "digital", "e-gram", "aadhar", "pan card", "online job", "सीएससी", "कंप्यूटर", "ସିଏସସି", "କମ୍ପ୍ୟୁଟର"]
  },
  {
    id: "job-4",
    title: "Data Entry & Beneficiary Records Operator",
    company: "Block Development Office / Mo Seva Kendra",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Bhawanipatna Block Office",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 12,000 – 18,000/month",
    salaryNumericMin: 12000,
    salaryNumericMax: 18000,
    badge: "Government",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["Fast Typing (30+ WPM)", "MS Excel & Google Sheets", "Data Portals", "Document Scanning"],
    category: "government",
    sectorId: "digital_construction",
    sectorName: "Digital, Infrastructure & Construction",
    nsqfLevel: 4,
    qpCode: "SSC/Q1401",
    trainingCourseId: "nsqf-course-csc-digital-gram",
    trainingCourseTitle: "Common Service Center (CSC) & Digital e-Gram Operator (NSQF Level 4)",
    subsidyGrant: "₹35,000 Digital Kiosk Subsidy",
    urgency: "normal",
    description: "Assist Block Development Office in verifying and digitizing beneficiary applications for PM-AJAY, PMAY-G housing, and Odisha Mo Seva welfare schemes.",
    openings: 12,
    experience: "10th/12th Pass with Computer Knowledge",
    benefits: ["Government Experience Certificate", "Fixed Working Hours (10 AM - 5 PM)", "Weekly Sunday Off", "Direct Bank Credit"],
    contactPhone: "+91 6670 220055",
    verifiedNCS: true,
    voiceKeywords: ["data entry", "computer operator", "typing", "block office", "डाटा एंट्री", "कंप्यूटर ऑपरेटर", "ଡାଟା ଏଣ୍ଟ୍ରି"]
  },
  {
    id: "job-jal-jeevan-plumber",
    title: "Jal Jeevan Mission Har Ghar Jal Pipeline Maintenance Plumber",
    company: "Rural Water Supply & Sanitation (RWSS) Department",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Gram Panchayat Level",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 24,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 24000,
    badge: "Jal Jeevan Mission",
    badgeColor: "blue",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["HDPE/PVC Jointing", "RO Membrane Descaling", "Leakage Detection", "Pump Fitting"],
    category: "government",
    sectorId: "digital_construction",
    sectorName: "Digital, Infrastructure & Construction",
    nsqfLevel: 3,
    qpCode: "PSC/Q0104",
    trainingCourseId: "nsqf-course-plumbing-water-plant",
    trainingCourseTitle: "Plumbing & Village RO Water Plant Operator (NSQF Level 3)",
    subsidyGrant: "₹35,000 Plumbing Tool Kit Grant",
    urgency: "immediate",
    description: "Maintain community tap water pipelines, repair underground leakage, service village RO water purification plants, and ensure clean drinking water across 500+ households.",
    openings: 20,
    experience: "8th / 10th Standard + Plumbing NSQF Certification",
    benefits: ["Gram Panchayat Annual Maintenance Contract (AMC)", "Full Mobile Plumbing Tool Chest", "Health Insurance"],
    contactPhone: "+91 6670 224810",
    verifiedNCS: true,
    voiceKeywords: ["plumber", "plumbing", "pipe", "jal jeevan", "water tap", "ro plant", "प्लंबर", "नल", "ପ୍ଲମ୍ବର", "ପାଣି ପାଇପ"]
  },
  {
    id: "job-cctv-wifi-tech",
    title: "Solar CCTV Surveillance & BharatNet Wi-Fi Maintenance Tech",
    company: "SecureGram Smart Surveillance Pvt. Ltd.",
    companyLogoType: "shree",
    type: "Full Time",
    location: "District Level",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 25,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 25000,
    badge: "Smart Village",
    badgeColor: "purple",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Solar 4G CCTV Mounting", "NVR Remote Configuration", "Point-to-Point Wi-Fi", "Cat-6 Cabling"],
    category: "private",
    sectorId: "digital_construction",
    sectorName: "Digital, Infrastructure & Construction",
    nsqfLevel: 4,
    qpCode: "ELE/Q4601",
    trainingCourseId: "nsqf-course-cctv-village-security",
    trainingCourseTitle: "Solar CCTV & Smart Village Wi-Fi Network Specialist (NSQF Level 4)",
    subsidyGrant: "₹35,000 CCTV Tooling Subsidy",
    urgency: "normal",
    description: "Install and maintain solar-powered outdoor IP cameras for schools, grain warehouses, and Gram Panchayats with remote smartphone NVR live view setup.",
    openings: 15,
    experience: "10th Pass with Electronics / Networking certification",
    benefits: ["Company Bike Allowance", "Tool Kit and Crimping Kit provided", "Performance bonus"],
    contactPhone: "+91 6670 255700",
    verifiedNCS: true,
    voiceKeywords: ["cctv", "camera", "wifi", "surveillance", "internet", "सीसीटीवी", "कैमरा", "ସିସିଟିଭି"]
  },
  {
    id: "job-pmay-master-mason",
    title: "PMAY-G Master Mason (Rajmistri) & Housing Inspector",
    company: "District Rural Development Agency (DRDA PMAY-G)",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Rural Blocks, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 20,000 – 30,000/month",
    salaryNumericMin: 20000,
    salaryNumericMax: 30000,
    badge: "PMAY-G Mission",
    badgeColor: "blue",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["Earthquake Resilient RCC", "Fly-Ash Brick Laying", "Bar Bending", "Geo-Tagging Inspection"],
    category: "government",
    sectorId: "digital_construction",
    sectorName: "Digital, Infrastructure & Construction",
    nsqfLevel: 4,
    qpCode: "CON/Q0102",
    trainingCourseId: "nsqf-course-masonry-flyash-brick",
    trainingCourseTitle: "Modern Masonry, Fly-Ash Brick & PMAY Rural Housing (NSQF Level 4)",
    subsidyGrant: "₹45,000 Hydraulic Brick Machine Grant",
    urgency: "immediate",
    description: "Lead construction of durable earthquake-resilient concrete houses under Pradhan Mantri Awas Yojana (PMAY-G), supervise bar bending, and validate Geo-tag photos.",
    openings: 45,
    experience: "Masons with 1+ Year experience or CSDC NSQF Level 4 Certificate",
    benefits: ["Highest rural daily wage rate (₹750-₹900/day)", "Government Registered Master Mason Certificate", "Free Safety Boots & Helmet"],
    contactPhone: "+91 6670 220330",
    verifiedNCS: true,
    voiceKeywords: ["mason", "masonry", "rajmistri", "pmay", "construction", "brick", "मिस्त्री", "राजमिस्त्री", "ମିସ୍ତ୍ରୀ", "ଘର ତିଆରି"]
  },

  // =========================================================================
  // 5. MICRO-ENTERPRISE & AGRO-PROCESSING MILLS
  // =========================================================================
  {
    id: "job-cold-press-oil-owner",
    title: "Kachi Ghani Cold-Press Mustard & Groundnut Oil Mill Owner",
    company: "PMFME Micro-Food Processing Livelihood Unit",
    companyLogoType: "ahaar",
    type: "Self-Employment",
    location: "Agro-Market Hub, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 32,000 – 65,000/month (Net)",
    salaryNumericMin: 32000,
    salaryNumericMax: 65000,
    badge: "PMFME Scheme",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Cold-Press Expeller", "Filter Press", "FSSAI Packaging", "Retail Mandi Tie-up"],
    category: "self_employment",
    sectorId: "micro_enterprise_grants",
    sectorName: "Agro-Mills & PM-AJAY Grants",
    nsqfLevel: 4,
    qpCode: "FIC/Q0103",
    trainingCourseId: "nsqf-course-cold-press-oil-mill",
    trainingCourseTitle: "Cold-Press Oil Expeller & Seed Processing (NSQF Level 4)",
    subsidyGrant: "₹50,000 PM-AJAY Subsidy + PMFME 35% Credit Grant",
    urgency: "high",
    description: "Extract pure chemical-free cold-pressed mustard, groundnut, and sesame oil using automated stainless steel expellers. Bottle, label with FSSAI QR codes, and sell to 40+ grocery stores.",
    openings: 18,
    experience: "10th Pass / Micro-Enterprise Aspirants",
    benefits: ["₹50,000 direct capital grant disbursal", "High 40–60% retail profit margin on cold-pressed oil", "Cattle feed oil-cake (Khal) secondary revenue"],
    contactPhone: "+91 6670 245012",
    verifiedNCS: true,
    voiceKeywords: ["oil mill", "mustard oil", "cold press", "oil expeller", "kachi ghani", "तेल मिल", "सरसों तेल", "ତେଲ ମିଲ"]
  },
  {
    id: "job-spice-pulverizer-lead",
    title: "Low-Temperature Spice Pulverization & Masala Packaging Lead",
    company: "Ahaar Pure Spices & Tribal Agri-Mill",
    companyLogoType: "ahaar",
    type: "Full Time",
    location: "District Food Park",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 25,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 25000,
    badge: "PMFME Supported",
    badgeColor: "amber",
    badgeIcon: "chart",
    image: "/dashboard/food_processing.jpg",
    skills: ["Water-Cooled Pulverizer", "Curcumin Testing", "Nitrogen Sealing", "FSSAI Safety"],
    category: "private",
    sectorId: "micro_enterprise_grants",
    sectorName: "Agro-Mills & PM-AJAY Grants",
    nsqfLevel: 4,
    qpCode: "FIC/Q0201",
    trainingCourseId: "nsqf-course-spice-pulverizer-unit",
    trainingCourseTitle: "Spice Pulverization & Masala Packaging Enterprise (NSQF Level 4)",
    subsidyGrant: "₹45,000 Micro-Pulverizer Capital Subsidy",
    urgency: "normal",
    description: "Operate low-temperature stainless steel spice pulverizers for pure turmeric, red chilli, and garam masala blends, nitrogen flush aluminum pouches, and ensure zero aroma loss.",
    openings: 16,
    experience: "Fresher / NSQF Level 4 Food Processing Certificate",
    benefits: ["PF & Health Insurance", "Quarterly Output Incentive", "FSSAI Food Safety Training Certificate"],
    contactPhone: "+91 6670 245199",
    verifiedNCS: true,
    voiceKeywords: ["spice", "masala", "pulverizer", "turmeric", "chilli", "grinding", "मसाला", "हल्दी", "ଚକି", "ମସଲା"]
  },
  {
    id: "job-millet-bakery-lead",
    title: "Shree Anna Millet Processing & POSHAN Nutrition Supply Partner",
    company: "Odisha Millet Mission & WCD Department",
    companyLogoType: "ahaar",
    type: "Self-Employment",
    location: "Block Level Centers",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 24,000 – 48,000/month (Net)",
    salaryNumericMin: 24000,
    salaryNumericMax: 48000,
    badge: "Shree Anna Mission",
    badgeColor: "amber",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Ragi/Millet Dehulling", "Rotary Baking Oven", "Gluten-Free Cookies", "Anganwadi Supply Contract"],
    category: "self_employment",
    sectorId: "micro_enterprise_grants",
    sectorName: "Agro-Mills & PM-AJAY Grants",
    nsqfLevel: 4,
    qpCode: "FIC/Q0801",
    trainingCourseId: "nsqf-course-millet-bakery",
    trainingCourseTitle: "Shree Anna Millet Processing & Bakery Hub (NSQF Level 4)",
    subsidyGrant: "₹45,000 Commercial Baking Unit Grant",
    urgency: "high",
    description: "Dehull indigenous Mandia (Ragi), bake fortified gluten-free millet cookies, muffins, and roasted snacks with guaranteed government procurement for Anganwadis and hostels.",
    openings: 25,
    experience: "Women SHG Members & Youth",
    benefits: ["Guaranteed bulk procurement by Odisha Millet Mission", "₹45,000 PM-AJAY capital subsidy", "Listing on ONDC"],
    contactPhone: "+91 6670 233800",
    verifiedNCS: true,
    voiceKeywords: ["millet", "mandia", "ragi", "shree anna", "bakery", "poshan", "मिलेट", "रागी", "ମାଣ୍ଡିଆ", "ମିଲେଟ୍"]
  },
  {
    id: "job-3",
    title: "Food Processing Assistant & Quality Packager",
    company: "Ahaar Food Products Ltd.",
    companyLogoType: "ahaar",
    type: "Full Time",
    location: "District Industrial Estate",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 14,000 – 20,000/month",
    salaryNumericMin: 14000,
    salaryNumericMax: 20000,
    badge: "Good Opportunity",
    badgeColor: "blue",
    badgeIcon: "chart",
    image: "/dashboard/food_processing.jpg",
    skills: ["Food Preservation", "Pickle Formulation", "Vacuum Sealing", "FSSAI Standards"],
    category: "private",
    sectorId: "micro_enterprise_grants",
    sectorName: "Agro-Mills & PM-AJAY Grants",
    nsqfLevel: 4,
    qpCode: "FIC/Q0103",
    trainingCourseId: "course-3",
    trainingCourseTitle: "Food Processing (NSQF Level 4)",
    subsidyGrant: "₹3,500/mo Stipend + FPO Linkage",
    urgency: "normal",
    description: "Operate agro-processing packaging units, clean and grade organic grains and pulses, manage batch labeling, and adhere to FSSAI hygienic standards.",
    openings: 20,
    experience: "Fresher / 10th Pass with Vocational Certificate",
    benefits: ["Health Insurance Cover", "FSSAI Training Certificate", "Annual Performance Bonus", "Day Shifts Only"],
    contactPhone: "+91 6670 245012",
    verifiedNCS: true,
    voiceKeywords: ["food processing", "packaging", "pickle", "preservation", "फूड प्रोसेसिंग", "खाद्य प्रसंस्करण", "ଖାଦ୍ୟ ପ୍ରକ୍ରିୟାକରଣ"]
  },

  // =========================================================================
  // 6. HEALTHCARE & COMMUNITY WELFARE
  // =========================================================================
  {
    id: "job-hospital-gda",
    title: "Hospital General Duty Assistant (GDA) & Patient Caregiver",
    company: "District Red Cross Hospital & Ayushman Health Center",
    companyLogoType: "odisha",
    type: "Full Time",
    location: "Bhawanipatna District Hospital",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 15,000 – 22,000/month",
    salaryNumericMin: 15000,
    salaryNumericMax: 22000,
    badge: "High Demand",
    badgeColor: "blue",
    badgeIcon: "building",
    image: "/dashboard/food_processing.jpg",
    skills: ["Patient Bedside Care", "Vitals Checking (BP/Sugar/SpO2)", "Infection Control", "Emergency CPR"],
    category: "government",
    sectorId: "healthcare_services",
    sectorName: "Healthcare & Community Welfare",
    nsqfLevel: 4,
    qpCode: "HSS/Q5101",
    trainingCourseId: "course-5",
    trainingCourseTitle: "Healthcare General Duty Assistant (NSQF Level 4)",
    subsidyGrant: "₹3,800/mo Stipend + Uniform Allowance",
    urgency: "immediate",
    description: "Assist doctors and staff nurses in OPD/IPD wards, measure patient vitals (BP, glucose, pulse), maintain sterile hygiene, and assist elderly patient mobility.",
    openings: 30,
    experience: "10th Pass with HSSC General Duty Assistant NSQF Certificate",
    benefits: ["Hospital Employee Health Coverage", "Fixed shift rotations", "Overtime allowance for festival duties"],
    contactPhone: "+91 6670 220410",
    verifiedNCS: true,
    voiceKeywords: ["hospital", "nurse", "gda", "patient care", "health assistant", "clinic", "अस्पताल", "नर्स", "ହସପିଟାଲ", "ସ୍ୱାସ୍ଥ୍ୟ ସେବକ"]
  },
  {
    id: "job-telemedicine-point-operator",
    title: "e-Sanjeevani Village Telemedicine & Diagnostic Point Operator",
    company: "Ayushman Bharat Digital Health Mission Hub",
    companyLogoType: "odisha",
    type: "Contract",
    location: "Gram Panchayat Health Wellness Center",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 16,000 – 25,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 25000,
    badge: "Digital Health",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/food_processing.jpg",
    skills: ["e-Sanjeevani Doctor Video Calls", "Point-of-Care Digital ECG", "Rapid Blood Testing", "ABHA ID Creation"],
    category: "government",
    sectorId: "healthcare_services",
    sectorName: "Healthcare & Community Welfare",
    nsqfLevel: 4,
    qpCode: "HSS/Q3401",
    trainingCourseId: "nsqf-course-telemedicine-operator",
    trainingCourseTitle: "Telemedicine & Village Diagnostic Point Operator (NSQF Level 4)",
    subsidyGrant: "₹40,000 Health Kiosk Capital Grant",
    urgency: "high",
    description: "Operate point-of-care digital medical devices (Digital ECG, Blood Sugar, Hemoglobin), facilitate remote specialist doctor video consultations on e-Sanjeevani, and dispense generic medicines.",
    openings: 20,
    experience: "10th / 12th Pass with Computer & Healthcare training",
    benefits: ["Commission per test and teleconsultation conducted", "Direct connection with AIIMS & District Specialist Doctors", "Solar UPS health kit"],
    contactPhone: "+91 6670 220919",
    verifiedNCS: true,
    voiceKeywords: ["telemedicine", "e-sanjeevani", "doctor call", "blood test", "ecg", "health clinic", "टेलीमेडिसिन", "ई-संजीवनी", "ଟେଲିମେଡିସିନ"]
  },
  {
    id: "job-ayush-herbal-distillation",
    title: "Ayush Herbal Essential Oil Distillation Unit Owner",
    company: "National Medicinal Plants Board (NMPB) Partner",
    companyLogoType: "shree",
    type: "Self-Employment",
    location: "Tribal Fringe Blocks, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 28,000 – 55,000/month (Net)",
    salaryNumericMin: 28000,
    salaryNumericMax: 55000,
    badge: "Ayush Mission",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/food_processing.jpg",
    skills: ["Steam Distillation Still", "Lemongrass Cultivation", "GC Purity Testing", "Pharmaceutical Buyback"],
    category: "self_employment",
    sectorId: "healthcare_services",
    sectorName: "Healthcare & Community Welfare",
    nsqfLevel: 4,
    qpCode: "AGR/Q0901",
    trainingCourseId: "nsqf-course-ayush-herbal-distillation",
    trainingCourseTitle: "Ayush Herbal Medicine & Essential Oil Distillation (NSQF Level 4)",
    subsidyGrant: "₹45,000 Distillation Still Capital Subsidy",
    urgency: "normal",
    description: "Grow organic lemongrass and tulsi on degraded soils, operate stainless steel steam distillation stills, extract pure therapeutic essential oils, and supply to Ayurvedic pharma companies (Dabur, Patanjali).",
    openings: 15,
    experience: "Open to Forest Farmers & Rural Youth",
    benefits: ["Pre-tied corporate buyback agreements (₹1,800–₹2,500/Litre)", "₹45,000 PM-AJAY capital grant", "High drought resilience"],
    contactPhone: "+91 6670 267100",
    verifiedNCS: true,
    voiceKeywords: ["ayush", "herbal", "lemongrass", "essential oil", "ayurveda", "distillation", "आयुष", "हर्बल तेल", "ଆୟୁଷ"]
  },
  {
    id: "job-6",
    title: "Mission Shakti SHG Community Mobilizer & Scheme Verifier",
    company: "Mission Shakti SHG Federation & PM-AJAY Cell",
    companyLogoType: "odisha",
    type: "Full Time",
    location: "Gram Panchayat Level",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 13,000 – 17,500/month",
    salaryNumericMin: 13000,
    salaryNumericMax: 17500,
    badge: "Government",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/tailoring.jpg",
    skills: ["Field Survey", "Community Mobilization", "Financial Literacy", "Odia/Hindi"],
    category: "government",
    sectorId: "healthcare_services",
    sectorName: "Healthcare & Community Welfare",
    nsqfLevel: 4,
    qpCode: "SSC/Q1401",
    trainingCourseId: "nsqf-course-csc-digital-gram",
    trainingCourseTitle: "Common Service Center (CSC) & Digital e-Gram Operator (NSQF Level 4)",
    subsidyGrant: "Smartphone + Travel Allowance",
    urgency: "normal",
    description: "Coordinate with village women SHGs, facilitate financial literacy camps, and verify scheme applications under PM-AJAY and Mission Shakti.",
    openings: 25,
    experience: "Local Village Resident preferred with communication skills",
    benefits: ["Monthly Travel Reimbursement", "Smartphone Allowance", "Maternity Benefit", "Govt ID Card"],
    contactPhone: "+91 6670 220114",
    verifiedNCS: true,
    voiceKeywords: ["community mobilizer", "field assistant", "mission shakti", "shg", "survey", "कम्युनिटी मोबिलाइजर", "ମିଶନ ଶକ୍ତି"]
  },

  // =========================================================================
  // 7. APPRENTICESHIP PROGRAMS (NAPS / NSDC)
  // =========================================================================
  {
    id: "job-naps-solar-apprentice",
    title: "NAPS Certified Solar Power Plant Maintenance Apprentice",
    company: "National Apprenticeship Promotion Scheme (NAPS)",
    companyLogoType: "shree",
    type: "Apprenticeship",
    location: "Rooftop & Farm Solar Grids, Kalahandi",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 11,500/month (Govt Stipend)",
    salaryNumericMin: 11500,
    salaryNumericMax: 11500,
    badge: "NAPS Stipend",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Solar Array Inspection", "Thermal Imaging", "Inverter Logging", "Safety Lockouts"],
    category: "apprenticeship",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "SGJ/Q0101",
    trainingCourseId: "course-4",
    trainingCourseTitle: "Solar PV Technician (Suryamitra)",
    subsidyGrant: "100% Free Training + Monthly DBT Stipend",
    urgency: "immediate",
    description: "Gain 6-month hands-on On-the-Job Training (OJT) on high-capacity solar plants with direct permanent placement conversion upon completion.",
    openings: 30,
    experience: "ITI Electrical / Wireman or NSQF Level 3/4 Graduates",
    benefits: ["NAPS National Apprenticeship Certificate", "Direct DBT stipend to Jan Dhan Bank Account", "Pre-placement offer (PPO) conversion"],
    contactPhone: "+91 6670 255880",
    verifiedNCS: true,
    voiceKeywords: ["apprentice", "apprenticeship", "naps", "solar apprentice", "stipend job", "अप्रेंटिस", "ସୋଲାର ଆପ୍ରେଣ୍ଟିସ"]
  },
  {
    id: "job-ohpc-electromechanical-apprentice",
    title: "Industrial ITI Electromechanical Apprentice",
    company: "Odisha Hydro Power Corporation (OHPC)",
    companyLogoType: "odisha",
    type: "Apprenticeship",
    location: "Hydro Power Station, Mukhiguda",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 12,000/month + Free Hostel",
    salaryNumericMin: 12000,
    salaryNumericMax: 12000,
    badge: "PSU Apprentice",
    badgeColor: "purple",
    badgeIcon: "building",
    image: "/dashboard/electrician.jpg",
    skills: ["Turbine Generator Wiring", "Hydraulic Actuators", "PLC Switchgear", "Industrial Safety"],
    category: "apprenticeship",
    sectorId: "green_energy_tech",
    sectorName: "Green Energy & Technical Trades",
    nsqfLevel: 4,
    qpCode: "ELE/Q5901",
    trainingCourseId: "course-1",
    trainingCourseTitle: "Electrician (NSQF Level 4)",
    subsidyGrant: "Free Hostel & Canteen",
    urgency: "high",
    description: "Undergo formal industrial apprenticeship at State PSU Hydro Plant. Work alongside chief electrical engineers on turbine switchgear and power transformers.",
    openings: 20,
    experience: "ITI Electrician / Fitter / Wireman passouts",
    benefits: ["PSU Experience Certificate", "Free On-campus Hostel & Subsidized Mess", "Priority in upcoming State DISCOM recruitments"],
    contactPhone: "+91 6670 227100",
    verifiedNCS: true,
    voiceKeywords: ["iti apprentice", "ohpc", "hydro apprentice", "psu job", "इलेक्ट्रीशियन अप्रेंटिस", "ଇଣ୍ଡଷ୍ଟ୍ରିଆଲ ଆପ୍ରେଣ୍ଟିସ"]
  },
  {
    id: "job-drone-ops-apprentice",
    title: "Kisan Drone Operations & Fleet Service Apprentice",
    company: "Directorate General of Civil Aviation (DGCA) Partner",
    companyLogoType: "shree",
    type: "Apprenticeship",
    location: "Kalahandi Drone Hub",
    district: "Kalahandi",
    state: "Odisha",
    salary: "₹ 14,000/month (Stipend)",
    salaryNumericMin: 14000,
    salaryNumericMax: 14000,
    badge: "Flight Logged",
    badgeColor: "purple",
    badgeIcon: "star",
    image: "/dashboard/electrician.jpg",
    skills: ["Drone Battery Swapping", "Propeller Balancing", "Flight Logging", "Emergency RTH"],
    category: "apprenticeship",
    sectorId: "agriculture_allied",
    sectorName: "Agriculture & Allied Enterprise",
    nsqfLevel: 4,
    qpCode: "AGR/Q4901",
    trainingCourseId: "nsqf-course-drone-pilot-agri",
    trainingCourseTitle: "Kisan Drone Pilot & Crop Health Analyst (NSQF Level 4)",
    subsidyGrant: "Free DGCA Pilot Hours Logging",
    urgency: "immediate",
    description: "Complete 100+ required agricultural drone flight log hours under certified DGCA flight instructors with free drone maintenance kit and food stipend.",
    openings: 15,
    experience: "Youth Age 18+ with 10th Standard Pass & Aadhaar",
    benefits: ["100% Free DGCA Pilot License Test", "Direct recruitment as Commercial Pilot upon 100 hours", "Free Drone Toolkit"],
    contactPhone: "+91 6670 270150",
    verifiedNCS: true,
    voiceKeywords: ["drone apprentice", "flight training", "drone stipend", "ड्रोन अप्रेंटिस", "ଡ୍ରୋନ୍ ତାଲିମ"]
  }
];

/**
 * Generate a dynamic verified Job opportunity from any detected beneficiary skill
 */
export function generateJobFromDetectedSkill(
  rawSkill: string,
  district: string = "Kalahandi",
  state: string = "Odisha",
  customProfile?: BeneficiaryProfileData
): EnrichedJobItem {
  const cleanSkill = (rawSkill || "Solar PV Specialist").trim();
  const lower = cleanSkill.toLowerCase();

  // 1. Try to match an existing job
  for (const job of COMPREHENSIVE_JOBS_DATABASE) {
    if (
      job.voiceKeywords.some((k) => lower.includes(k) || k.includes(lower)) ||
      job.skills.some((s) => lower.includes(s.toLowerCase())) ||
      lower.includes(job.title.toLowerCase())
    ) {
      return {
        ...job,
        id: `detected-job-${lower.replace(/[^a-z0-9]/g, "-")}`,
        location: `${district}, ${state}`,
        district: district,
        state: state,
        isDetectedJob: true,
        detectedReason: `Specially matched to your verified background in ${cleanSkill}`
      };
    }
  }

  // 2. Synthesize custom verified job
  const isAgri = /agri|farm|crop|plant|soil|livestock|dairy|goat|poultry|fish|seed|honey|bee|mushroom|spice|oil|millet/i.test(lower);
  const isHandicraft = /craft|bamboo|pottery|artisan|tailor|cloth|handloom|wood|jewel|garment|beauty|salon/i.test(lower);
  const isHealth = /health|nurse|care|patient|medic|ayush|doctor|clinic|telemed/i.test(lower);
  const isDigital = /digital|comput|csc|web|it|plumb|mason|construct|cctv/i.test(lower);

  const sectorId = isAgri
    ? "agriculture_allied"
    : isHandicraft
      ? "crafts_textiles"
      : isHealth
        ? "healthcare_services"
        : isDigital
          ? "digital_construction"
          : "green_energy_tech";

  const sectorName = isAgri
    ? "Agriculture & Allied Enterprise"
    : isHandicraft
      ? "Handicrafts & Women SHG"
      : isHealth
        ? "Healthcare & Community Welfare"
        : isDigital
          ? "Digital, Infrastructure & Construction"
          : "Green Energy & Technical Trades";

  const image = isAgri ? "/dashboard/food_processing.jpg" : isHandicraft ? "/dashboard/tailoring.jpg" : "/dashboard/electrician.jpg";

  return {
    id: `detected-job-${lower.replace(/[^a-z0-9]/g, "-")}`,
    title: `${cleanSkill} Specialist & Lead Operator`,
    company: `${district} Regional Enterprise & Skill Hub`,
    companyLogoType: "shree",
    type: "Full Time",
    location: `${district}, ${state}`,
    district: district,
    state: state,
    salary: "₹ 16,000 – 26,000/month",
    salaryNumericMin: 16000,
    salaryNumericMax: 26000,
    badge: "✨ Verified Skill Match",
    badgeColor: "emerald",
    badgeIcon: "star",
    image: image,
    skills: [cleanSkill, "Quality Assurance", "Practical Safety", "Digital Payments"],
    category: "private",
    sectorId: sectorId,
    sectorName: sectorName,
    nsqfLevel: 4,
    qpCode: `SKL/Q${Math.abs(cleanSkill.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0) % 8999) + 1000}`,
    trainingCourseTitle: `${cleanSkill} (NSQF Level 4)`,
    subsidyGrant: "₹35,000 PM-AJAY Micro-Enterprise Grant",
    urgency: "immediate",
    description: `Verified career opportunity synthesized for ${cleanSkill}. Perform domain tasks, handle customer requirements in ${district}, and earn competitive monthly wages with scheme grants.`,
    openings: 20,
    experience: customProfile?.education ? `${customProfile.education} or practical experience` : "Freshers with verified skill",
    benefits: ["PF + ESI Coverage", "PM-AJAY Capital Tool Kit subsidy", "Direct bank wage transfer"],
    contactPhone: "+91 6670 220011",
    verifiedNCS: true,
    voiceKeywords: [lower, cleanSkill.toLowerCase()],
    isDetectedJob: true,
    detectedReason: `Synthesized for detected skill: ${cleanSkill}`
  };
}

/**
 * Get personalized job list including dynamically detected opportunities matching beneficiary profile
 */
export function getPersonalizedJobsForProfile(
  profile: BeneficiaryProfileData | null,
  baseJobs: EnrichedJobItem[] = COMPREHENSIVE_JOBS_DATABASE
): {
  detectedJobs: EnrichedJobItem[];
  allJobs: EnrichedJobItem[];
  detectedSkillName: string | null;
} {
  const detectedSkills: string[] = [];

  if (profile) {
    if (profile.nsqfCourse && profile.nsqfCourse.trim().length > 0) {
      detectedSkills.push(profile.nsqfCourse);
    }
    if (profile.skills && profile.skills.length > 0) {
      profile.skills.forEach((s) => {
        if (s && s.trim().length > 0 && !detectedSkills.includes(s)) {
          detectedSkills.push(s);
        }
      });
    }
    if (profile.aspiration && profile.aspiration.trim().length > 0 && !detectedSkills.includes(profile.aspiration)) {
      detectedSkills.push(profile.aspiration);
    }
  }

  // Also check localStorage if in browser
  if (typeof window !== "undefined" && detectedSkills.length === 0) {
    try {
      const saved = localStorage.getItem("Sakhyam_beneficiary_profile");
      if (saved) {
        const parsed: BeneficiaryProfileData = JSON.parse(saved);
        if (parsed.nsqfCourse) detectedSkills.push(parsed.nsqfCourse);
        if (parsed.skills) parsed.skills.forEach((s) => detectedSkills.push(s));
      }
    } catch { }
  }

  const generatedJobs: EnrichedJobItem[] = [];
  const seenTitles = new Set<string>();

  for (const skill of detectedSkills) {
    const clean = skill.replace(/\(.*?\)/g, "").trim();
    if (clean.length > 2 && !seenTitles.has(clean.toLowerCase())) {
      seenTitles.add(clean.toLowerCase());
      const customJob = generateJobFromDetectedSkill(
        clean,
        profile?.district || "Kalahandi",
        profile?.state || "Odisha",
        profile || undefined
      );
      generatedJobs.push(customJob);
    }
  }

  const combined = [...generatedJobs];
  const catalogToUse = baseJobs.length > 0 ? baseJobs : COMPREHENSIVE_JOBS_DATABASE;

  catalogToUse.forEach((bj) => {
    const bjTitleClean = bj.title.replace(/\(.*?\)/g, "").toLowerCase().trim();
    const isAlreadyCovered = generatedJobs.some((gj) => {
      const gjTitleClean = gj.title.replace(/\(.*?\)/g, "").toLowerCase().trim();
      return gjTitleClean.includes(bjTitleClean) || bjTitleClean.includes(gjTitleClean);
    });
    if (!isAlreadyCovered) {
      combined.push(bj);
    }
  });

  return {
    detectedJobs: generatedJobs,
    allJobs: combined,
    detectedSkillName: detectedSkills.length > 0 ? detectedSkills[0] : null
  };
}

/**
 * Fast search & matching of jobs by natural language or voice queries
 */
export function searchJobsByQuery(
  query: string,
  jobsList: EnrichedJobItem[] = COMPREHENSIVE_JOBS_DATABASE,
  filterCategory: string = "all"
): EnrichedJobItem[] {
  if (!query || !query.trim()) {
    if (filterCategory === "all") return jobsList;
    return jobsList.filter((j) => j.category === filterCategory || j.sectorId === filterCategory);
  }

  const q = query.toLowerCase().trim();
  return jobsList.filter((job) => {
    const matchesCategory =
      filterCategory === "all" ||
      job.category === filterCategory ||
      job.sectorId === filterCategory;

    const matchesText =
      job.title.toLowerCase().includes(q) ||
      job.company.toLowerCase().includes(q) ||
      job.location.toLowerCase().includes(q) ||
      job.description.toLowerCase().includes(q) ||
      job.skills.some((s) => s.toLowerCase().includes(q)) ||
      job.voiceKeywords.some((k) => k.toLowerCase().includes(q) || q.includes(k.toLowerCase()));

    return matchesCategory && matchesText;
  });
}
